---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: sb-extended
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/secureblue/kinoite-main-hardened
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: kargs
    kargs:
      - ia32_emulation=1 # Allow 32bit support for Steam
      - nosmt=force # Force disable SMT/Multi-threading
  
  - type: dnf
    install:
      packages:
        - trivalent-qt6-ui
        - kde-connect
        - chromium
        - chromium-qt6-ui
        - syncthing
        - steam
        - gamescope
        - mangohud
        - libreoffice
        - protontricks
        - strawberry
        - gwenview
        - haruna
        - kamoso
        - kcalc
        - okular
        - bottles
        - wine
        - winetricks
        - kernel-devel # VirtualBox
        - kernel-headers # VirtualBox
        - gcc # VirtualBox
        - make # VirtualBox
        - elfutils-libelf-devel # VirtualBox
        - https://download.virtualbox.org/virtualbox/7.2.6/VirtualBox-7.2-7.2.6_172322_fedora40-1.x86_64.rpm # VirtualBox
        - android-tools # adb, fastboot
        - https://proton.me/download/mail/linux/1.12.1/ProtonMail-desktop-beta.rpm
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - ark

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.usebottles.bottles
          - com.github.tchx84.Flatseal
          - io.github.peazip.PeaZip
          - org.signal.Signal
          - io.github.flattool.Warehouse
          - net.davidotek.pupgui2
          - net.retrodeck.retrodeck
          - io.ente.photos
          - com.ktechpit.whatsie
          - io.github.astralvixen.geforce-infinity
          - com.visualstudio.code
          - com.vscodium.codium
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
